/**
 * GENERATED by tools/fetch-stills.mjs --urls — do not edit by hand.
 *
 * Still URLs on TMDB's CDN, keyed by the slug in js/frames-data.js. Nothing is
 * stored in this repository; these point at TMDB, which licenses stills for
 * this use and requires the attribution line in README.md.
 *
 * Regenerate:  TMDB_API_KEY=... node tools/fetch-stills.mjs --urls
 */

export const STILL_URLS = {
  'shawshank-redemption': [
    'https://image.tmdb.org/t/p/w1280/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
    'https://image.tmdb.org/t/p/w1280/v8xVDqt8uCul3c3mgx4VpGCwxJC.jpg',
    'https://image.tmdb.org/t/p/w1280/pNjh59JSxChQktamG3LMp9ZoQzp.jpg',
    'https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
  ],
  '12-angry-men': [
    'https://image.tmdb.org/t/p/w1280/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
    'https://image.tmdb.org/t/p/w1280/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg',
    'https://image.tmdb.org/t/p/w1280/p1nBxgrSu9Ex0Uvci1ItWWCWPlk.jpg',
    'https://image.tmdb.org/t/p/w1280/y50XKChhmU8rHBBwc7jKwN5Qf6m.jpg',
  ],
  'schindlers-list': [
    'https://image.tmdb.org/t/p/w1280/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
    'https://image.tmdb.org/t/p/w1280/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg',
    'https://image.tmdb.org/t/p/w1280/w2ezhZUk7ZJH9Mdk1Y6CTmaDRg5.jpg',
    'https://image.tmdb.org/t/p/w1280/gXvNfaetPlZt3PUPsBFcfZuoUFe.jpg',
  ],
  'pulp-fiction': [
    'https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    'https://image.tmdb.org/t/p/w1280/cOGysF4SXauEKz18mFGmkZW6O2T.jpg',
    'https://image.tmdb.org/t/p/w1280/9pGM43a9VmXxwIxmhJoiDkcB2hT.jpg',
    'https://image.tmdb.org/t/p/w1280/w7RDIgQM6bLT7JXtH4iUQd3Iwxm.jpg',
  ],
  'fight-club': [
    'https://image.tmdb.org/t/p/w1280/c6OLXfKAk5BKeR6broC8pYiCquX.jpg',
    'https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
    'https://image.tmdb.org/t/p/w1280/xRyINp9KfMLVjRiO5nCsoRDdvvF.jpg',
    'https://image.tmdb.org/t/p/w1280/52AfXWuXCHn3UjD17rBruA9f5qb.jpg',
  ],
  'inception': [
    'https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    'https://image.tmdb.org/t/p/w1280/ii8QGacT3MXESqBckQlyrATY0lT.jpg',
    'https://image.tmdb.org/t/p/w1280/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
    'https://image.tmdb.org/t/p/w1280/gqby0RhyehP3uRrzmdyUZ0CgPPe.jpg',
    'https://image.tmdb.org/t/p/w1280/28kKbSUvUz6P5RE1AuMJMO7IMfK.jpg',
  ],
  'the-matrix': [
    'https://image.tmdb.org/t/p/w1280/tlm8UkiQsitc8rSuIAscQDCnP8d.jpg',
    'https://image.tmdb.org/t/p/w1280/oMsxZEvz9a708d49b6UdZK1KAo5.jpg',
    'https://image.tmdb.org/t/p/w1280/8K9qHeM6G6QjQN0C5XKFGvK5lzM.jpg',
    'https://image.tmdb.org/t/p/w1280/oCkOhekO65sH5o3UnnWPStYHEnv.jpg',
  ],
  'interstellar': [
    'https://image.tmdb.org/t/p/w1280/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg',
    'https://image.tmdb.org/t/p/w1280/8sNiAPPYU14PUepFNeSNGUTiHW.jpg',
    'https://image.tmdb.org/t/p/w1280/vgnoBSVzWAV9sNQUORaDGvDp7wx.jpg',
    'https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    'https://image.tmdb.org/t/p/w1280/pbrkL804c8yAv3zBZR4QPEafpAR.jpg',
  ],
  'one-battle-after-another': [
    'https://image.tmdb.org/t/p/w1280/zpEWFNqoN8Qg1SzMMHmaGyOBTdW.jpg',
    'https://image.tmdb.org/t/p/w1280/hiazLNa1UXuX35OTnMQRKOx3eTk.jpg',
    'https://image.tmdb.org/t/p/w1280/gre7gyocZSuwd7M51CGlqsJqBmB.jpg',
    'https://image.tmdb.org/t/p/w1280/si68lkhkMfIospVeLEBtl7HWKDh.jpg',
  ],
  'the-departed': [
    'https://image.tmdb.org/t/p/w1280/6WRrGYalXXveItfpnipYdayFkQB.jpg',
    'https://image.tmdb.org/t/p/w1280/cDFtxTxEtE3ljadfQ5SwtRTi8Iw.jpg',
    'https://image.tmdb.org/t/p/w1280/9RuC3UD6mNZ0p1J6RbfJDUkQ03i.jpg',
    'https://image.tmdb.org/t/p/w1280/bbT3xRFp0tX66e6X0eiQW3zRk1q.jpg',
  ],
  'across-the-spider-verse': [
    'https://image.tmdb.org/t/p/w1280/9xfDWXAUbFXQK585JvByT5pEAhe.jpg',
    'https://image.tmdb.org/t/p/w1280/kVd3a9YeLGkoeR50jGEXM6EqseS.jpg',
    'https://image.tmdb.org/t/p/w1280/nGxUxi3PfXDRm7Vg95VBNgNM8yc.jpg',
    'https://image.tmdb.org/t/p/w1280/jbthbh0KzaUWFPYvkfmXAamjI8j.jpg',
    'https://image.tmdb.org/t/p/w1280/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
  ],
  'django-unchained': [
    'https://image.tmdb.org/t/p/w1280/2oZklIzUbvZXXzIFzv7Hi68d6xf.jpg',
    'https://image.tmdb.org/t/p/w1280/s4cJQaj40SwMifUrrdtdOJsjnRO.jpg',
    'https://image.tmdb.org/t/p/w1280/n2eUT4zQA2yYcKOgAFidgOyiFoH.jpg',
    'https://image.tmdb.org/t/p/w1280/5Lbm0gpFDRAPIV1Cth6ln9iL1ou.jpg',
  ],
  'memento': [
    'https://image.tmdb.org/t/p/w1280/7Wev9JMo6R5XAfz2KDvXb7oPMmy.jpg',
    'https://image.tmdb.org/t/p/w1280/8pwCb7amg8Tvr9FZZJGt7J4OwLV.jpg',
    'https://image.tmdb.org/t/p/w1280/v4u9FnSOpLEjPIAhbKClM45LJoJ.jpg',
    'https://image.tmdb.org/t/p/w1280/q2CtXYjp9IlnfBcPktNkBPsuAEO.jpg',
  ],
  'infinity-war': [
    'https://image.tmdb.org/t/p/w1280/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg',
    'https://image.tmdb.org/t/p/w1280/k3xGG77CAiB0Wr2Y1H3ApihKTkk.jpg',
    'https://image.tmdb.org/t/p/w1280/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg',
    'https://image.tmdb.org/t/p/w1280/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg',
  ],
  'dune-part-two': [
    'https://image.tmdb.org/t/p/w1280/eZ239CUp1d6OryZEBPnO2n87gMG.jpg',
    'https://image.tmdb.org/t/p/w1280/rRBD8ORo9y34tYkAQJVbn4Ml6tu.jpg',
    'https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
    'https://image.tmdb.org/t/p/w1280/WZCfWFlKnGKZy9Bdf1rdEQDGkc.jpg',
    'https://image.tmdb.org/t/p/w1280/24Ov8wnusgnzXwjV1eDm0Lzo5da.jpg',
  ],
  'endgame': [
    'https://image.tmdb.org/t/p/w1280/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
    'https://image.tmdb.org/t/p/w1280/91iy9F1JOG1dvM6M6JNYgvScZpK.jpg',
    'https://image.tmdb.org/t/p/w1280/9wXPKruA6bWYk2co5ix6fH59Qr8.jpg',
    'https://image.tmdb.org/t/p/w1280/orjiB3oUIsyz60hoEqkiGpy5CeO.jpg',
  ],
  'coco': [
    'https://image.tmdb.org/t/p/w1280/g7CHF8gTLGooTbP4GznIGwaqAGL.jpg',
    'https://image.tmdb.org/t/p/w1280/bnkf3C2ZMF6i7MLOemWqEHDMqfh.jpg',
    'https://image.tmdb.org/t/p/w1280/lxfCCC41yC4KEHBYtB7E0YsWA9c.jpg',
    'https://image.tmdb.org/t/p/w1280/gKZAQ3b9yApxFunUBlS5Mp74QG4.jpg',
  ],
  'dark-knight-rises': [
    'https://image.tmdb.org/t/p/w1280/y2DB71C4nyIdMrANijz8mzvQtk6.jpg',
    'https://image.tmdb.org/t/p/w1280/2PKMeD171nYXR3J77fD3GKl1zfl.jpg',
    'https://image.tmdb.org/t/p/w1280/c3OHQncTAnKFhdOTX7D3LTW6son.jpg',
    'https://image.tmdb.org/t/p/w1280/d354XqicJ7vi48YnPDr1vRk5uhZ.jpg',
  ],
  'your-name': [
    'https://image.tmdb.org/t/p/w1280/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg',
    'https://image.tmdb.org/t/p/w1280/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
    'https://image.tmdb.org/t/p/w1280/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg',
    'https://image.tmdb.org/t/p/w1280/rjs5IfIv6Psl2YCSHKcluhTQGjJ.jpg',
    'https://image.tmdb.org/t/p/w1280/blEF6I5n7X0GXMfv8fFl1o0Tz3z.jpg',
  ],
  'oldboy': [
    'https://image.tmdb.org/t/p/w1280/sdwjQEM869JFwMytTmvr6ggvaUl.jpg',
    'https://image.tmdb.org/t/p/w1280/tcbzsdWpdidbN7zbOymlRKfIHVg.jpg',
    'https://image.tmdb.org/t/p/w1280/47rioCQJLDe6gT7NYdPf7IRy3Nu.jpg',
    'https://image.tmdb.org/t/p/w1280/hKNGaQFzg4RxyMWIGGnYGW5b2Xh.jpg',
  ],
  '3-idiots': [
    'https://image.tmdb.org/t/p/w1280/8gT3UKtglLVpu0YfccwbmXZ5Eis.jpg',
    'https://image.tmdb.org/t/p/w1280/wDrQOaIYrTHAteGlFATfZtU3m3o.jpg',
    'https://image.tmdb.org/t/p/w1280/7fqChpiaXELdOBGHVJaEoetS7dw.jpg',
    'https://image.tmdb.org/t/p/w1280/u7kuUaySqXBVAtqEl9vkTkAzHV9.jpg',
  ],
  'joker': [
    'https://image.tmdb.org/t/p/w1280/rlay2M5QYvi6igbGcFjq8jxeusY.jpg',
    'https://image.tmdb.org/t/p/w1280/hw1CwteUFGjcWXwjGhKk8UJpWeA.jpg',
    'https://image.tmdb.org/t/p/w1280/hO7KbdvGOtDdeg0W4Y5nKEHeDDh.jpg',
    'https://image.tmdb.org/t/p/w1280/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg',
  ],
  'incendies': [
    'https://image.tmdb.org/t/p/w1280/f3ATwil5vmUeTsogBaMEKbBYBth.jpg',
    'https://image.tmdb.org/t/p/w1280/u8wmr8QCowIYXUxVeZYSPWVbB9P.jpg',
    'https://image.tmdb.org/t/p/w1280/xsmOd7CnT6XrfQoRTF3YVeS0ByJ.jpg',
    'https://image.tmdb.org/t/p/w1280/xzuiKws8WQ5wYlIm4gDPX7mzvtf.jpg',
  ],
  'up': [
    'https://image.tmdb.org/t/p/w1280/hGGC9gKo7CFE3fW07RA587e5kol.jpg',
    'https://image.tmdb.org/t/p/w1280/vmU4aluI4SYiPIYC5ghqXAu29tK.jpg',
    'https://image.tmdb.org/t/p/w1280/mH9IXGi80ySUDkxl7uwsKNwqcyC.jpg',
    'https://image.tmdb.org/t/p/w1280/h8C7KZwCJO5DN7jPifc7AoIjx7k.jpg',
  ],
  'like-stars-on-earth': [
    'https://image.tmdb.org/t/p/w1280/bPwdy3zaNnMdZ22u0WCcYu0xxgt.jpg',
    'https://image.tmdb.org/t/p/w1280/5dF4FNwM2qZIuF0WCUs5zvDGU2H.jpg',
    'https://image.tmdb.org/t/p/w1280/owqarJSDllJGoEW8EMz8q6cvKDD.jpg',
    'https://image.tmdb.org/t/p/w1280/d3QJlk6YNijPzMT5gIAJuszVpcM.jpg',
  ],
  'aot-last-attack': [
    'https://image.tmdb.org/t/p/w1280/sl5rXSyMTzK5WkpRO9oVIkqr6DE.jpg',
    'https://image.tmdb.org/t/p/w1280/a4It6nWFmGw6P76B67FZndaecXS.jpg',
    'https://image.tmdb.org/t/p/w1280/wZY7MFeDcJR1It2ywanCKQudnvt.jpg',
    'https://image.tmdb.org/t/p/w1280/dReyvVudZ0PLl8mSw8zyLr6O4eC.jpg',
  ],
};
